// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<frc::SpeedController> RobotMap::movimientoMIzqAtras;
std::shared_ptr<frc::SpeedController> RobotMap::movimientoMDerAdel;
std::shared_ptr<frc::SpeedController> RobotMap::movimientoMDerAtras;
std::shared_ptr<frc::SpeedController> RobotMap::movimientoMIzqAdel;
std::shared_ptr<frc::MecanumDrive> RobotMap::movimientoMovimientoMecano;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    movimientoMIzqAtras.reset(new frc::Spark(0));
    lw->AddActuator("Movimiento", "MIzqAtras", std::static_pointer_cast<frc::Spark>(movimientoMIzqAtras));
    
    movimientoMDerAdel.reset(new frc::Spark(1));
    lw->AddActuator("Movimiento", "MDerAdel", std::static_pointer_cast<frc::Spark>(movimientoMDerAdel));
    
    movimientoMDerAtras.reset(new frc::Spark(2));
    lw->AddActuator("Movimiento", "MDerAtras", std::static_pointer_cast<frc::Spark>(movimientoMDerAtras));
    
    movimientoMIzqAdel.reset(new frc::Spark(3));
    lw->AddActuator("Movimiento", "MIzqAdel", std::static_pointer_cast<frc::Spark>(movimientoMIzqAdel));
    
    movimientoMovimientoMecano.reset(new frc::MecanumDrive(*movimientoMIzqAdel, *movimientoMIzqAtras,
              *movimientoMDerAdel, *movimientoMDerAtras));
    lw->AddActuator("Movimiento", "MovimientoMecano", movimientoMovimientoMecano);
    movimientoMovimientoMecano->SetSafetyEnabled(false);
        movimientoMovimientoMecano->SetExpiration(0.1);
        movimientoMovimientoMecano->SetMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
